<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "hop_envios_map": {
                        "component": "Hop_Envios/js/view/hop",
                        "template" : "Hop_Envios/hop-map"
                    }
                }
            }
        }
    }
</script>

<div id="hop-popup-modal" style="display: none;">
    <div id="selector-maps-hop">
        <div id="selector-sucursal">
            <div class="input-buscador-hop">
                <input type="text" name="buscador" id="buscador-hop" placeholder="Buscá por calle o barrio" "/>
            </div>
        </div>
        <div id="points-maps-hop" style=""></div>
    </div>
    <div id="google-maps-hop" style=""></div>
</div>
